#set-up fake database
spring.datasource.url=jdbc:h2:mem://localhost:3306/fc_repo
spring.datasource.driver-class-name=org.h2.Driver
# Change l'URL de Swagger UI
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.path=/docs
# Choix par défaut pour éviter warning
spring.jpa.open-in-view=true